### ISSUE TITLE
Build for IOS fails

### ISSUE THREAD

**Issue by royibernthal** [Ingenio/flutter_pubnub#19]
I'm getting an error when I'm trying to build the app for ios using `flutter build ios`.

**Xcode's output:**
```
In file included from /Users/administrator/Desktop/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_pubnub-0.3.1/ios/Classes/PubnubPlugin.m:1:
    /Users/administrator/Desktop/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_pubnub-0.3.1/ios/Classes/PubnubPlugin.h:4:9: fatal error: 'PubNub/PubNub.h' file not found
    #import <PubNub/PubNub.h>
            ^~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description
```

**Comment by appdevingenio** [comment]
On your project or in the plugin example folder?

**Comment by royibernthal** [comment]
It happens in my own project.

Are there any special configurations I'm supposed to take from the example folder?

**Comment by olivierbrand** [comment]
Can you build the example app in our plugin directory? It seems that cocoapod did not kick in for you as it cannot find the includes. I am sure you have tried to execute: flutter clean? 
Can you share your Yaml file?

**Comment by royibernthal** [comment]
I was able to build your example app without any problems.

I tried executing `flutter clean` both on my project and on the isolated project with just pubnub in it (https://github.com/Ingenio/flutter_pubnub/issues/20), and I'm still getting the same errors.


Here's the pubspec.yaml of my actual project:

```
name: myappname
description: A new Flutter application.

version: 0.1.4+4

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^3.1.0
  uuid: ^2.0.2
  cached_network_image: ^2.0.0-rc
  image_picker: ^0.6.3+4
  flutter_form_builder: ^3.5.5
  video_player: ^0.10.8+1
  pin_input_text_field: ^3.0.1
  flutter_icons: ^0.3.1
  quiver: ^2.1.3
  password_strength: ^0.1.2
  permission_handler: ^4.4.0
  dio: ^3.0.9
  event_bus: ^1.1.1
  shared_preferences: ^0.5.6+2
  flutter_pubnub: ^0.3.2
  flushbar: ^1.9.1
  firebase_messaging: ^6.0.12
  firebase_crashlytics: ^0.1.3
  get_it: ^4.0.0
  http_parser: ^3.1.3
  flutter_dotenv: ^2.1.0
  crypto: ^2.1.4
  package_info: ^0.4.0+14
  flutter_uploader: ^1.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  
flutter:
  
  uses-material-design: true

  fonts:
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto/Roboto-Regular.ttf
         - asset: assets/fonts/Roboto/Roboto-RegularItalic.ttf
           style: italic
         - asset: assets/fonts/Roboto/Roboto-Bold.ttf
           weight: 700
         - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
           weight: 700
           style: italic
     - family: Mansalva
       fonts:
        - asset: assets/fonts/Mansalva/Mansalva-Regular.ttf


  assets:
    - dev.env
    - prod.env
    - assets/icon/icon.png
```

And here's the pubspec.yaml of the isolated project with just flutter_pubnub:

```
name: testios2
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.2
  flutter_pubnub: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  
  uses-material-design: true
```

The only difference I noticed so far is in your pubspec.yaml you write the flutter dependency as follows:

```
flutter_pubnub:
    path: ../
```

And you put it under dev_dependecies instead of dependencies (why?)

While I write it like that, under dependencies:

`flutter_pubnub: ^0.3.2`

If instead I do it exactly like you, I'm getting the following error when I execute `flutter pub get`:

> Could not find a file named "pubspec.yaml" in "/Users/administrator/AndroidStudioProjects".
> pub get failed (66; Could not find a file named "pubspec.yaml" in "/Users/administrator/AndroidStudioProjects".)

It appears that in its path you are referring to the pubspec.yaml at the root folder (outside of the example dir). Not sure I fully understand why (perhaps to not redownload the dependency for the example project since it already exists in its parent folder?), but maybe it's part of the reason things are working for the example project and not for a new project?
